# Generated by Django 5.1.1 on 2024-10-14 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_alter_todo_is_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='details',
        ),
    ]
