# Generated by Django 5.1.1 on 2024-09-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('details', models.CharField(max_length=300)),
                ('is_checked', models.BooleanField()),
                ('deadline', models.DateField()),
            ],
        ),
    ]
