# Generated by Django 4.2.16 on 2024-09-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
